language: python

python:
    - "3.7"

env:
  global:
    - CODECOV_TOKEN='f8c5eff3-c7b2-440f-8540-bf6a7330b822'

services:
    - mysql

before_install:
  - mysql -e 'DROP DATABASE IF EXISTS applicationtrackingsystem'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS applicationtrackingsystem;'
  - mysql -u root --default-character-set=utf8 applicationtrackingsystem < database/SET_DATABASE.sql
  - cd backend

install:
  - pip3 install -r requirements.txt
  - pip3 install pytest-cov

before_script:
  - nohup flask run &
  - jobs

script:
    - pytest -v backend --cov=./ --cov-report=xml

after_success:
    - codecov

deploy:
  - provider: heroku
    api_key: 3f7a58cc-5c30-4f84-a90f-5225109c9a6e
    app: application-tracking-system
