language: python
python:
    - "3.7"
install:
    - pip install -r backend/requirements.txt
    - cd frontend
    - npm install || true
    - cd ../
    - cd backend
    - flask run
services:
    - mysql
sudo: true
before_script:
    - bash .travis.install-mysql-5.7.sh
script:
    - pwd
    - python -m pytest
    - cd ..
    - coverage run --source=backend -m pytest backend
    - coveralls --service=github
