language: python
python:
    - "3.7"
install:
    - pip install -r backend/requirements.txt
    - pip install codecov
    - cd frontend
    - npm install || true
    - cd ../
    - cd backend
    - flask run
services:
    - mysql
sudo: true
before_script:
    - bash .travis.install-mysql-5.7.sh
script:
    - pwd
    - python -m pytest
    - cd ..
    - coverage run --source=backend -m pytest backend
    - coveralls --service=github
after_success:
    - codecov
deploy:
  - provider: heroku
    api_key: 3f7a58cc-5c30-4f84-a90f-5225109c9a6e
    app: application-tracking-system
