sudo: enabled

language: python

python:
  - "3.6"

os:
  - linux

services:
  - mysql

# install dependencies
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS applicationtrackingsystem'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS applicationtrackingsystem;'  
  - mysql -u root --default-character-set=utf8 applicationtrackingsystem < database/SET_DATABASE.sql
  - cd backend

install:
  - pip3 install -r requirements.txt
  - nohup flask run 
script:
    - python -m pytest

#  - pytest
   
after_success:
  - coveralls
##
