
name: PyTest

on:
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r ./backend/requirements.txt
    - name: Test with pytest, upload to codecov
      run: |
        cd ./backend
        pytest --cov-report xml:cov.xml --cov=./ ./
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true